TAGS = [
    # Methods
    ("Large Language Models", "method"),
    ("Computer Vision", "method"),
    ("Reinforcement Learning", "method"),
    ("NLP", "method"),
    ("Forecasting", "method"),
    ("Optimization", "method"),
    ("Recommendation Systems", "method"),
    ("Anomaly Detection", "method"),
    ("Generative AI", "method"),
    ("Multi-Agent Systems", "method"),
    ("RAG", "method"),
    ("Fine-Tuning", "method"),
    ("Federated Learning", "method"),
    ("Graph Neural Networks", "method"),
    ("Time Series", "method"),
    ("Causal Inference", "method"),

    # Domains
    ("Economics", "domain"),
    ("Operations Research", "domain"),
    ("Efficiency", "domain"),
    ("Supply Chain", "domain"),
    ("Pricing", "domain"),
    ("Automation", "domain"),
    ("Decision Making", "domain"),
    ("Resource Allocation", "domain"),
    ("Scheduling", "domain"),
    ("Risk Management", "domain"),
    ("Quality Control", "domain"),
    ("Demand Forecasting", "domain"),
    ("Process Optimization", "domain"),
    ("Cost Reduction", "domain"),
    ("Productivity", "domain"),

    # Industries
    ("Healthcare", "industry"),
    ("Finance", "industry"),
    ("Manufacturing", "industry"),
    ("Retail", "industry"),
    ("Energy", "industry"),
    ("Transportation", "industry"),
    ("Agriculture", "industry"),
    ("Education", "industry"),
    ("Logistics", "industry"),
    ("Telecommunications", "industry"),
    ("Real Estate", "industry"),
    ("Legal", "industry"),
    ("Insurance", "industry"),
    ("Pharmaceuticals", "industry"),
    ("Construction", "industry"),
    ("Media", "industry"),

    # Applications
    ("Production System", "application"),
    ("Research Tool", "application"),
    ("Decision Support", "application"),
    ("Process Automation", "application"),
    ("Predictive Maintenance", "application"),
    ("Customer Service", "application"),
    ("Fraud Detection", "application"),
    ("Document Processing", "application"),
    ("Code Generation", "application"),
    ("Search & Retrieval", "application"),
]

COMPANIES = [
    {"name": "Google DeepMind", "aliases": '["DeepMind", "Google Brain"]', "website": "https://deepmind.google", "sector": "big_tech"},
    {"name": "OpenAI", "aliases": "[]", "website": "https://openai.com", "sector": "startup"},
    {"name": "Anthropic", "aliases": "[]", "website": "https://anthropic.com", "sector": "startup"},
    {"name": "Meta AI", "aliases": '["FAIR", "Meta FAIR"]', "website": "https://ai.meta.com", "sector": "big_tech"},
    {"name": "Microsoft Research", "aliases": '["MSR"]', "website": "https://www.microsoft.com/en-us/research/", "sector": "big_tech"},
    {"name": "Amazon AWS AI", "aliases": '["AWS AI", "Amazon Science"]', "website": "https://aws.amazon.com/ai/", "sector": "big_tech"},
    {"name": "Apple ML", "aliases": '["Apple Machine Learning"]', "website": "https://machinelearning.apple.com", "sector": "big_tech"},
    {"name": "NVIDIA Research", "aliases": '["NVIDIA"]', "website": "https://www.nvidia.com/en-us/research/", "sector": "big_tech"},
    {"name": "Cohere", "aliases": "[]", "website": "https://cohere.com", "sector": "startup"},
    {"name": "Mistral AI", "aliases": '["Mistral"]', "website": "https://mistral.ai", "sector": "startup"},
    {"name": "Stability AI", "aliases": "[]", "website": "https://stability.ai", "sector": "startup"},
    {"name": "Hugging Face", "aliases": '["HuggingFace"]', "website": "https://huggingface.co", "sector": "startup"},
    {"name": "Scale AI", "aliases": "[]", "website": "https://scale.com", "sector": "startup"},
    {"name": "Databricks", "aliases": '["Mosaic ML"]', "website": "https://databricks.com", "sector": "startup"},
    {"name": "Salesforce Research", "aliases": '["Salesforce AI"]', "website": "https://www.salesforceairesearch.com", "sector": "big_tech"},
    {"name": "IBM Research", "aliases": '["IBM"]', "website": "https://research.ibm.com", "sector": "big_tech"},
    {"name": "Baidu Research", "aliases": '["Baidu"]', "website": "https://research.baidu.com", "sector": "big_tech"},
    {"name": "Tencent AI Lab", "aliases": '["Tencent"]', "website": "https://ai.tencent.com", "sector": "big_tech"},
    {"name": "ByteDance Research", "aliases": '["ByteDance"]', "website": "https://www.bytedance.com", "sector": "big_tech"},
    {"name": "Samsung Research", "aliases": '["Samsung AI"]', "website": "https://research.samsung.com", "sector": "big_tech"},
    {"name": "Uber AI", "aliases": "[]", "website": "https://www.uber.com/us/en/about/science/", "sector": "big_tech"},
    {"name": "Spotify Research", "aliases": "[]", "website": "https://research.atspotify.com", "sector": "big_tech"},
    {"name": "Netflix Research", "aliases": "[]", "website": "https://research.netflix.com", "sector": "big_tech"},
    {"name": "Airbnb", "aliases": "[]", "website": "https://medium.com/airbnb-engineering", "sector": "big_tech"},
    {"name": "Stripe", "aliases": "[]", "website": "https://stripe.com", "sector": "big_tech"},
    {"name": "Letta", "aliases": '["MemGPT"]', "website": "https://letta.com", "sector": "startup"},
    {"name": "Adept AI", "aliases": '["Adept"]', "website": "https://adept.ai", "sector": "startup"},
    {"name": "Inflection AI", "aliases": '["Inflection"]', "website": "https://inflection.ai", "sector": "startup"},
    {"name": "Character AI", "aliases": "[]", "website": "https://character.ai", "sector": "startup"},
    {"name": "Runway", "aliases": '["Runway ML"]', "website": "https://runwayml.com", "sector": "startup"},
    {"name": "Weights & Biases", "aliases": '["W&B", "wandb"]', "website": "https://wandb.ai", "sector": "startup"},
    {"name": "Anyscale", "aliases": "[]", "website": "https://anyscale.com", "sector": "startup"},
    {"name": "Modal", "aliases": "[]", "website": "https://modal.com", "sector": "startup"},
    {"name": "Palantir", "aliases": "[]", "website": "https://palantir.com", "sector": "big_tech"},
    {"name": "C3.ai", "aliases": "[]", "website": "https://c3.ai", "sector": "startup"},
    {"name": "DataRobot", "aliases": "[]", "website": "https://datarobot.com", "sector": "startup"},
    {"name": "xAI", "aliases": '["Grok"]', "website": "https://x.ai", "sector": "startup"},
]

RSS_FEEDS = [
    {"url": "https://openai.com/blog/rss.xml", "company": "OpenAI"},
    {"url": "https://deepmind.google/blog/rss.xml", "company": "Google DeepMind"},
    {"url": "https://engineering.fb.com/feed/", "company": "Meta AI"},
    {"url": "https://www.microsoft.com/en-us/research/feed/", "company": "Microsoft Research"},
    {"url": "https://aws.amazon.com/blogs/machine-learning/feed/", "company": "Amazon AWS AI"},
    {"url": "https://blog.research.google/feeds/posts/default", "company": "Google DeepMind"},
    {"url": "https://www.anthropic.com/research/rss.xml", "company": "Anthropic"},
    {"url": "https://machinelearning.apple.com/rss.xml", "company": "Apple ML"},
    {"url": "https://blogs.nvidia.com/feed/", "company": "NVIDIA Research"},
    {"url": "https://research.ibm.com/blog/rss", "company": "IBM Research"},
    {"url": "https://txt.cohere.com/rss/", "company": "Cohere"},
    {"url": "https://mistral.ai/feed.xml", "company": "Mistral AI"},
    {"url": "https://stability.ai/blog/rss.xml", "company": "Stability AI"},
    {"url": "https://huggingface.co/blog/feed.xml", "company": "Hugging Face"},
    {"url": "https://www.databricks.com/feed", "company": "Databricks"},
    {"url": "https://blog.salesforceairesearch.com/rss/", "company": "Salesforce Research"},
    {"url": "https://research.netflix.com/rss", "company": "Netflix Research"},
    {"url": "https://research.atspotify.com/feed/", "company": "Spotify Research"},
]
